title: inter alia
author: Arjun Attam
email: arjun@attam.in
description: >- # this means to ignore newlines until "baseurl:"
  Among other things.
baseurl: "/" # the subpath of your site
url: "https://arjun.is"
twitter_username: arjunattam
github_username:  arjun27

permalink: /:year/:title

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
