title: Arjun Attam
author: Arjun Attam
email: arjun@attam.in

baseurl: "/" # the subpath of your site
url: "https://arjun.is"
permalink: /:year/:title

twitter_username: arjunattam
github_username:  arjun27
google_analytics: UA-76439340-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
